import {
  CDN_URL,
  CLIENT_NAME,
  CONTACT_ADDRESS,
  CONTACT_EMAIL,
  CONTACT_PHONE_NUMBER,
  FACEBOOK_URL,
  GOOGLE_MAPS_LOCATION,
  REQUEST_ASSISTANCE_PDF_FILENAME,
  SERVICES_GATEWAY_URL
} from "./config";

export {
  CDN_URL,
  CLIENT_NAME,
  CONTACT_ADDRESS,
  CONTACT_EMAIL,
  CONTACT_PHONE_NUMBER,
  FACEBOOK_URL,
  GOOGLE_MAPS_LOCATION,
  REQUEST_ASSISTANCE_PDF_FILENAME,
  SERVICES_GATEWAY_URL
};
